set search_path to supercharge;


INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (100,'USA','US',100,true,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (101,'Canada','CA',100,true,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (102,'Austria','AT',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (103,'Germany','DE',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (104,'Netherlands','NL',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (105,'Norway','NO',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (106,'Switzerland','CH',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (107,'Denmark','DK',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (108,'United Kingdom','GB',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (109,'Sweden','SE',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (110,'France','FR',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (111,'Slovenia','SI',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (112,'Belgium','BE',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (113,'Italy','IT',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (114,'Japan','JP',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (115,'China','CN',102,true,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (116,'Australia','AU',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (117,'Spain','ES',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (118,'Luxembourg','LU',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (119,'Poland','PL',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (120,'Finland','FI',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (121,'Croatia','HR',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (122,'Slovakia','SK',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (123,'Czech Republic','CZ',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (124,'Ireland','IE',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (125,'Portugal','PT',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (126,'Hungary','HU',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (127,'Bulgaria','BG',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (128,'Turkey','TR',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (129,'Jordan','JO',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (130,'Russia','RU',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (131,'Mexico','MX',100,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (133,'Taiwan','TW',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (134,'United Arab Emirates','AE',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (135,'Ukraine','UA',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (136,'Estonia','EE',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (137,'South Korea','KR',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (138,'New Zealand','NZ',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (139,'India','IN',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (140,'Latvia','LV',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (141,'Lithuania','LT',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (142,'Moldova','MD',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (143,'Liechtenstein','LI',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (144,'Kazakhstan','KZ',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (145,'Romania','RO',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (146,'Greece','GR',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (147,'Bosnia and Herzegovina','BA',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (148,'Serbia','RS',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (149,'Albania','AL',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (151,'Belarus','BY',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (152,'Georgia','GE',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (153,'Saudi Arabia','SA',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (154,'Uzbekistan','UZ',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (155,'Iceland','IS',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (156,'Singapore','SG',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (157,'Israel','IL',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (158,'Morocco','MA',101,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (159,'Thailand','TH',102,false,now());
INSERT INTO country (country_id,"name",code,region_id,state_required,modified_date) VALUES (160,'Malaysia','MY',102,false,now());

-- pre-populate valid plug types per country
UPDATE country SET plugs_gbt = false WHERE name != 'China';
UPDATE country SET plugs_tpc = false, plugs_nacs = false, plugs_ccs1 = false WHERE region_id IN (101, 102) AND name NOT IN ('Japan', 'South Korea', 'Taiwan');
UPDATE country SET plugs_type2 = false, plugs_ccs2 = false WHERE region_id = 100 OR name IN ('Japan', 'South Korea');
UPDATE country SET plugs_ccs1 = false WHERE name IN ('Japan', 'Taiwan');
